routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*Route::get('/MasPopulares', function () {
    return view('MasPopulares.index');
});*/
/*Route::get('/ListadoSocios', function () {
    return view('Socios.index');
});



});*/



Auth::routes();

/*Route::get('/', function () {
    return view('layouts.app');
});*/
Route::get('/', function () {
    return view('/auth/login');
});

Route::group(['middleware'=>['auth']],function (){

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/MasPopulares', 'MasPopularesController');
    Route::resource('/Socios', 'SociosController');
    Route::resource('/ListaEsperas', 'ListaEsperasController');
    Route::resource('/Devoluciones', 'DevolucionesController');
    Route::resource('/Renta', 'RentadePeliculasController');
    Route::resource('/cart','RentadePeliculasController');
    Route::resource('/Generos','GenerosController');
    Route::resource('/GenFav','GenfavController');
    Route::resource('/DirFav','DirfavController');
    Route::resource('/Directores','DirectoresController');
    Route::resource('/Actores','ActoresController');
    Route::resource('/Peliculas','PeliculasController');

    Route::get('add-to-cart/{id_pelicula}','MasPopularesController@addToCart');
    Route::get('delete-cart/{id_pelicula}','MasPopularesController@delete');
    
    Route::get('show',[
        'as' => 'cart-show',
        'uses' => 'MasPopularesController@show']);

    Route::get('order-detail',[
        'middleware' => 'auth',
        'as' => 'order-detail',
        'uses' => 'RentadePeliculasController@orderDetail'
    ]);
});

app/ListaEsperas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ListaEsperas extends Model
{
    protected $table='listaespera';

    protected $fillable  = ['fecha_registro','id_pelicula','id_socio','estado'];

    protected $PK = 'id_espera';
}    

app/Http/Controllers/ListaEsperasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\ListaEsperas;
use App\Peliculas;
use App\Socios;
use App\Personas;

class ListaEsperasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = trim($request->get('search'));
        $prestar=trim($request->get('llamar'));
        $presta=1;
        $listado = DB::select('SELECT * FROM socios s,listaespera l,peliculas p,generos g,directores d WHERE s.id_socio=l.id_socio and l.id_pelicula=p.id_pelicula and p.id_genero=g.id_genero and p.id_director= d.id_director and  p.titulo like ' . "'%" . $query . "%'" . ' ORDER by l.estado asc');
        if(!$prestar==null)
        {
            DB::select('CALL llamadadisponible(?)',[$prestar]);
            return view('ListaEsperas.index', ['peliculas' => $listado, 'search' => $query]);
        }else if(!$presta==null)
        {
            DB::select('CALL llamadadisponible(?)',[$prestar]);
            return view('ListaEsperas.index', ['peliculas' => $listado, 'search' => $query]);
        }
        return view('ListaEsperas.index', ['peliculas' => $listado, 'search' => $query]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ListaEsperas.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    }

    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\MasPopulares  $masPopulares
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lista = ListaEsperas::findOrFail($id);
        return view('ListaEsperas.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\MasPopulares  $masPopulares
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $masPopulares)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\MasPopulares  $masPopulares
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $lista = DB::delete('DELETE FROM `listaespera` WHERE `listaespera`.`id_espera` = ?', $lista->id_persona);
        return redirect('ListaEsperas')->with('Registro eliminado con exito');;
    }
}

resources/views/ListaEsperas/create.blade.php
@extends('Template/empleados')
@section('content')
    <div class="container">
        <h2 class="text-center card-title font-weight-normal mt-5">Lista de Espera</h2>
        <div class="table-responsive card card-body mt-5">
            <form action="{{route('ListaEsperas.store')}}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                    <div class="form-group row">
                        <label for="Pelicula" class="col-md-4 col-form-label text-md-right">{{'Pelicula'}}</label>
                        <div class="col-md-6">
                            <select id="id_pelicula" class="form-control" name="Pelicula">
                                <option>Seleccionar Pelicula</option>
                                @foreach ($peliculas as $pelicula)
                                    <option value="{{ $pelicula['id_pelicula'] }}">{{ $pelicula['titulo'] }}</option>
                                @endforeach    
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">    
                        <label for="Fecha" class="col-md-4 col-form-label text-md-right">{{'Fecha de Pedido'}}</label>
                        <div class="col-md-6">
                            <input class="form-control" type="date" name="fecha_registro">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Socio" class="col-md-4 col-form-label text-md-right">{{'Socio'}}</label>
                        <div class="col-md-6">
                            <select id="id_socio" class="form-control" name="Socio">
                                <option>Seleccionar Socio</option>
                                @foreach ($socios as $socio)
                                    <option value="{{ $socio['id_socio'] }}">{{ $socio['id_persona'] }}</option>
                                @endforeach  
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="Estado" class="col-md-4 col-form-label text-md-right">{{'Estado'}}</label>
                        <div class="col-md-6">
                            <select id="estado" class="form-control" name="estado">
                                <option>Seleccionar Estado</option>
                                <option>disponible</option>
                                <option>no disponible</option>
                            </select>
                        </div>
                    </div>        
        </div>
            <br>
                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        <a href="{{url('/ListaEsperas')}}" type="submit" rel="tooltip" class="btn btn-primary">
                            <i class="fa fa-user-plus" >{{ __('Registrar') }}</i>
                        </a>
                    </div>
                </div>     
</form>
@endsection

resources/views/ListaEsperas/edit.blade.php
@extends('Template/empleados')
@section('content')
    <div class="container">
        <h2 class="text-center card-title font-weight-normal mt-5">Lista de Espera</h2>
        <div class="table-responsive card card-body mt-5">
            <div class="form-group row">
                     <label for="Pelicula" class="col-md-4 col-form-label text-md-right">{{'Pelicula'}}</label>
                    <div class="col-md-6">
                        <select id="id_pelicula" class="form-control" name="Pelicula">
                            <option>Seleccionar Pelicula</option>
                        </select>
                     </div>
            </div>
            <div class="form-group row">    
                    <label for="Fecha" class="col-md-4 col-form-label text-md-right">{{'Fecha de Pedido'}}</label>
                    <div class="col-md-6">
                        <input class="form-control" type="date" name="fecha_registro">
                    </div>
            </div>
            <div class="form-group row">
                     <label for="Socio" class="col-md-4 col-form-label text-md-right">{{'Socio'}}</label>
                    <div class="col-md-6">
                        <select id="id_socio" class="form-control" name="Socio">
                            <option>Seleccionar Socio</option>
                        </select>
                     </div>
            </div>
            <div class="form-group row">
                     <label for="Estado" class="col-md-4 col-form-label text-md-right">{{'Estado'}}</label>
                    <div class="col-md-6">
                        <select id="Estado" class="form-control" name="Estado">
                            <option>Estado</option>
                        </select>
                     </div>
            </div>        
        </div>
        <br>
            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <a href="{{url('/ListaEsperas')}}" type="submit" rel="tooltip" class="btn btn-primary">
                            <i class="fa fa-user-plus" >{{ __('Editar') }}</i>
                   </a>
                </div>
            </div>
    </div>
@endsection

resources/views/ListaEsperas/index.blade.php
@extends('Template/template')
@section('title', 'Lista de Espera')
@section('content')
<div class="col-12" class="container-fluid">
    <div class="row">
        <div class="col-12">
            <br>
            <h2 class="text-center card-title font-weight-normal ">Lista de Espera</h2>
        </div>
        <div class="col-4">
            <label>Buscar Pelicula</label>
            <form class="form-inline">
                <input type="search" name="search" placeholder="Buscar Pelicula" class="form-control" arial-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-info btn-round" type="submit">Buscar</button>

                </div>
                <div class="col">
                <a href="{{url('/ListaEsperas')}}" class="btn btn-info border-0" aria-pressed="false" autocomplete="off"><i class="fas fa-sync"></i></a>

                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="table-responsive card card-body mt-5">
            <table class="table table-light" class="table table-striped table-sm">
                <thead class="thead-light">
                    <tr>
                        <th>Fecha de Registro</th>
                        <th>Socio</th>
                        <th>Pelicula</th>
                        <th>Estado</th>
                        <th>Llamar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($peliculas as $lista)

                    <tr>
                        <td>{{$lista->fecha_registro}}</td>
                        <td>{{$lista->name}} {{$lista->ap_paterno}} {{$lista->ap_materno}}</td>
                        <td>{{$lista->titulo}}</td>
                        <td>{{$lista->estado}}</td>
                        <td>
                            <form class="form-inline" method="get">
                            @if(($lista->estado=="Disponible") || ($lista->estado=="disponible"))
                            <input type="text" name="llamar" value="{{$lista->id_espera}}" hidden>
                            <button class="btn btn-info btn-round" type="submit" onclick="return confirm('Su numero de telefono es:  {{$lista->telefono}}');"><i class="material-icons">phone</i></button>

                            <!-- <a href="{{url('/Generos/'.$lista->id_espera.'/create') }}" type="submit" rel="tooltip" class="btn btn-info btn-round" onclick="return alert('Su numero de telefono es:  {{$lista->telefono}}');"><i class="material-icons">phone</i></a> -->
                            @endif
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection