routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*Route::get('/MasPopulares', function () {
    return view('MasPopulares.index');
});*/
/*Route::get('/ListadoSocios', function () {
    return view('Socios.index');
});



});*/



Auth::routes();

/*Route::get('/', function () {
    return view('layouts.app');
});*/
Route::get('/', function () {
    return view('/auth/login');
});

Route::group(['middleware'=>['auth']],function (){

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/MasPopulares', 'MasPopularesController');
    Route::resource('/Socios', 'SociosController');
    Route::resource('/ListaEsperas', 'ListaEsperasController');
    Route::resource('/Devoluciones', 'DevolucionesController');
    Route::resource('/Renta', 'RentadePeliculasController');
    Route::resource('/cart','RentadePeliculasController');
    Route::resource('/Generos','GenerosController');
    Route::resource('/GenFav','GenfavController');
    Route::resource('/DirFav','DirfavController');
    Route::resource('/Directores','DirectoresController');
    Route::resource('/Actores','ActoresController');
    Route::resource('/Peliculas','PeliculasController');

    Route::get('add-to-cart/{id_pelicula}','MasPopularesController@addToCart');
    Route::get('delete-cart/{id_pelicula}','MasPopularesController@delete');
    
    Route::get('show',[
        'as' => 'cart-show',
        'uses' => 'MasPopularesController@show']);

    Route::get('order-detail',[
        'middleware' => 'auth',
        'as' => 'order-detail',
        'uses' => 'RentadePeliculasController@orderDetail'
    ]);
});

app/Peliculas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Peliculas extends Model
{
    //
    protected $table='peliculas';
    protected $primaryKey='id_pelicula';
    protected $fillable=['titulo','id_director','id_genero', 'cantidad'];

    function getDirector(){
        return $this->hasMany("App\Directores",'id_director','id_director');
    }
    function getGenero(){
        return $this->hasMany("App\Generos",'id_genero','id_genero');
    }
    public $timestamps=false;
}

app/Http/Controllers/PeliculasController.php
<?php

namespace App\Http\Controllers;
use App\Directores;
use App\Generos;
use App\Peliculas;
use Illuminate\Http\Request;


class PeliculasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if($request){
            $query = trim($request->get('search'));
            $Peliculas = Peliculas::where('titulo', 'LIKE', '%' . $query . '%')
            ->orderBy('titulo', 'asc')
            ->get();

            return view('Peliculas.index',['Peliculas' => $Peliculas, 'search' => $query]);
        }
        //$Peliculas=Peliculas:: orderby('id_pelicula')->get();
        //return view("Peliculas.index",compact("Peliculas"));
        //return view('Peliculas.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //return view('Peliculas.registrar');
        $Directores=Directores::all();
        $Generos=Generos::all();
        return view("Peliculas.create",compact("Directores", "Generos"));


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        /*$Pelicula = new Peliculas;*/

        $v = \validator($request->all(), [

            'titulo' => 'required|unique:Peliculas',
            'id_director' => 'required',
            'id_genero'    => 'required',
            'cantidad' => 'required'


        ]);

        if ($v->fails())
        {
            return redirect()->back()->withInput()->withErrors($v->errors());
        }

        Peliculas::create($request->all());
        /*$Pelicula = Peliculas::all();*/
        return redirect("Peliculas");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Peliculas  $peliculas
     * @return \Illuminate\Http\Response
     */
    public function show(Peliculas $peliculas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Peliculas  $peliculas
     * @return \Illuminate\Http\Response
     */
    public function edit(Peliculas $Pelicula)
    {
        //
        $Directores=Directores::all();
        $Generos=Generos::all();
        return view("Peliculas.edit",compact('Pelicula','Directores','Generos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Peliculas  $peliculas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Peliculas $Pelicula)
    {
        //
        $Pelicula->update($request->all());
        return redirect("Peliculas");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Peliculas  $peliculas
     * @return \Illuminate\Http\Response
     */
    public function destroy(Peliculas $Pelicula)
    {
        //
        $Pelicula->delete();
        return redirect("Peliculas");
    }

    public function bucador(Request $request)
    {
        //
        $titulo = Peliculas::where("titulo","like",$request->texto."%")->take(10)->get() ;
        return view("Peliculas.index",compact("Peliculas"));
    }
}

resources/views/Peliculas/create.blade.php
@extends('Template/template')
@section('title', 'Registro de Peliculas')
@section('content')
<div class="container-fluid">
	<meta charset="utf-8">
    <h3 class="centrar">Registro de Peliculas</h3>
    @if($errors->any())
    <div class="alert alert-danger">
        <h6>Corrige los errores para continuar:</h6>
    </div>

    @endif
    <div class="row">
        <div class="col"><a class="btn btn-primary" href="{{url("Peliculas")}}"><i class="fas fa-reply"></i> Regresar</a></div>
    </div>

    <div class="">
	    <form method="POST"action="{{url("Peliculas")}}">
            @csrf
  		    <div class="form-row">
    		    <div class="form-group col-md-4">
      			    <label for="titulo">Título:</label>
      			    <input type="text" id="titulo" class="form-control" name="titulo" placeholder="Título">
                </div>
                @if ($errors->has('titulo'))

                    <p>{{$errors->first('titulo')}}</p>

                @endif
    		   
            </div>
            <div class="form-group col-md-4">
                    <label for="nombre_dire">Director:</label>
                    <table>
                        <th><select class="form-control" name="id_director" id="">
                                <option value="">Elige una opcion</option>
                                @foreach($Directores as $Directore)
                                    <option value="{{$Directore->id_director}}">{{$Directore->nombre_dire}}</option>
                                @endforeach
                        </select></th>
                    </table>
  			    </div>
  		    <div class="form-row">
  			    <div class="form-group col-md-4">
                    <label for="des_gen">Genero:</label>
                    <table>
                        <th><select class="form-control" name="id_genero" id="">
                                <option value="">Elige una opcion</option>
                                @foreach($Generos as $Genero)
                                    <option value="{{$Genero->id_genero}}">{{$Genero->des_gen}}</option>
                                @endforeach
                            </select></th>
                    </table>
                </div>
                <div class="form-group col-md-4">
      			    <label for="cantidad">Copias:</label>
      			    <input type="integer" id="cantidad" class="form-control" name="cantidad" placeholder="Copias">
    		    </div>
              </div>
              
            <button type="submit" class="btn btn-primary">Guardar</button>
	    </form>
    </div>
</div>
@endsection

resources/views/Peliculas/edit.blade.php
@extends('Template/template')
@section('title', 'Editar de Peliculas')
@section('content')
    <div class="container-fluid">
        <meta charset="utf-8">
        <h3 class="centrar">Editar de Pelicula</h3>
        <div class="row">
            <div class="col"><a class="btn btn-primary" href="{{url("Peliculas")}}"><i class="fas fa-reply"></i> Regresar</a></div>
        </div>

        <div class="">
            <form method="POST" action="{{route("Peliculas.update",$Pelicula->id_pelicula)}}">
                @csrf
                @method("PUT")
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="titulo">Título:</label>
                        <input type="text" value="{{$Pelicula->titulo}}" id="titulo" class="form-control" name="titulo" placeholder="Título">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="nombre_dire">Director:</label>
                        <table>
                            <th><select class="form-control" name="id_director" id="">
                                    <option value="">Elige una opcion</option>
                                    @foreach($Directores as $Directore)
                                        <option value="{{$Directore->id_director}}" {{$Directore->id_director==$Pelicula->id_director?"selected":""}}>{{$Directore->nombre_dire}}</option>
                                    @endforeach
                                </select></th>
                        </table>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="des_gen">Genero:</label>
                        <table>
                            <th><select class="form-control" name="id_genero" id="">
                                    <option value="">Elige una opcion</option>
                                    @foreach($Generos as $Genero)
                                        <option value="{{$Genero->id_genero}}" {{$Genero->id_genero==$Pelicula->id_genero?"selected":""}}>{{$Genero->des_gen}}</option>
                                    @endforeach
                                </select></th>
                        </table>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="cantidad">Copias:</label>
                        <input type="integer" value="{{$Pelicula->cantidad}}" id="cantidad" class="form-control" name="cantidad" placeholder="copias">
                </div>
                </div>
                
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>
@endsection

resources/views/Peliculas/index.blade.php
@extends('Template/template')
@section('title', 'Peliculas')
@section('content')
    <div class="container">
    @if($errors->any())

    <p>Hay errores!</p>

    @endif

        <span class="float-right mt-2">
            <a href="{{url('/Peliculas/create')}}" type="button" rel="tooltip" class="btn btn-info btn-round">
                <i class="fa fa-user-plus" >    Registrar <br> Pelicula</i>
            </a>
        </span>
        <h2 class="text-center card-title font-weight-normal mt-5">Peliculas</h2>
        <div class="col-4">
            <label>Buscar Pelicula</label>
            <form class="form-inline">
                <input type="search" name="search" placeholder="Buscar Pelicula" class="form-control" arial-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-info btn-round" type="submit">Buscar</button>
                </div>
            </form>
        </div>
        <div class="table-responsive card card-body mt-5">
            <table class="table table-light" class="table table-striped table-sm">
                <thead class="thead-light">
                <tr>
                    <th>Título</th>
                    <th>Director</th>
                    <th>Genero</th>
                    <th>Copias</th>

                    <th>Acciones</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($Peliculas as $Pelicula)
                <tr>
                    <td>{{$Pelicula->titulo}}</td>
                    <td>{{$Pelicula->getDirector[0]?$Pelicula->getDirector[0]->nombre_dire:""}}</td>
                    <td>{{$Pelicula->getGenero[0]?$Pelicula->getGenero[0]->des_gen:""}}</td>
                    <td>{{$Pelicula->cantidad}}</td>
                    <div>

                    <td>
                        <a href="{{route("Peliculas.edit",$Pelicula->id_pelicula)}}"  class="btn btn-info btn-round">
                            <i class="material-icons">edit</i>
                            Editar
                        </a>

                    </td>
                    <td>
                        <form action="{{url("Peliculas")."/".$Pelicula->id_pelicula}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-dark btn-round" name="eliminar"><i class="material-icons">restore_from_trash</i>Eliminar</button>

                        </form>
                    </td>

                    </div>

                </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <script>
        window.addEventListener("load",function(){
            document.getElementById("texto").addEventListener("keyup",function(){
                fetch(` /Peliculas/buscador?texto=${document.getElementById("texto").value}`,{
                method:'get'
                })
                .then(response => response.text())
                .then(html => {
                document.getElementById("resultados").innerHTML = html
                })
            })
        })
    </script>
@endsection

resources/views/Peliculas/registrar.blade.php
@extends('Template/template')
@section('title', 'Registro de Peliculas')
@section('content')

<div class="container-fluid">
	<meta charset="utf-8">
	<h3 class="centrar">Registro de Peliculas</h3>
	
	<form>
  		<div class="form-row">
    		<div class="form-group col-md-4">
      			<label for="txtTitulo">Título:</label>
      			<input type="text" class="form-control" id="txtTitulo" placeholder="Título">
    		</div>
    		<div class="form-group col-md-4">
    			<label for="txtDirector">Director:</label>
          <select class="form-control">
            <option>Elige una opcion</option>
            <option>John</option>
          </select>
  			</div>
  		</div>
  		<div class="form-row">
  			<div class="form-group col-md-4">
    			<label for="txtGenero">Genero:</label>
    			<select class="form-control">
            <option>Elige una opcion</option>
            <option>John</option>
          </select>
    		</div>
  		</div>
		  <div class="form-group col-md-4">
      			<label for="intcantidad">Copias:</label>
      			<input type="integer" class="form-control" id="intcantidad" placeholder="cantidad">
    		</div> 
  		<div class="form-row">
  			<div class="form-group col-md-4">
  				<button type="submit" class="btn btn-primary">Limpiar</button>
  				<button type="submit" class="btn btn-primary">Guardar</button>
  				<button type="submit" class="btn btn-primary">Cancelar</button>
  			</div>
  		</div>
	</form>
</div>
@endsection